<a href="https://colab.research.google.com/github/Anvarjondevelop/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print('numpy_arr', arr)

numpy_arr [1 2 3 4]


In [5]:
arr2 = np.array([[1,2,3,4],[6,7,8,9]])
print('numpy_arr2', arr2)

arr.shape

numpy_arr2 [[1 2 3 4]
 [6 7 8 9]]


(4,)

In [6]:
#dtype
a = np.array([1,2,3])
print(a.dtype)

int64


In [7]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print('array_reshaped:',b)

array_reshaped: [[1 2 3]
 [4 5 6]]


In [8]:
#astype
a = np.array([1,2,3])
b = a.astype(float)
print(b)

[1. 2. 3.]


In [11]:
# np.zeros(), np.ones() => dummy data
z = np.zeros((2,3))
o = np.ones((2,3))

print(z)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#ndim
a = np.array([[1,3], [2,4]])
print(a.ndim)

2


In [14]:
#arange
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [16]:
#sum #mean #min #max
a = np.array([1,2,3,4])

print(a.sum())
print(a.mean())
print(a.min())
print(a.max())


10
2.5
1
4


In [17]:
#flatten
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.flatten())


[1 2 3 4 5 6 7 8]


In [19]:
# Transpose
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.T)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [20]:
#dot /@
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
print('dot/multiplication:', a.dot(b))

dot/multiplication: [[16 19]
 [36 43]]


In [22]:
#random.rand
a = np.random.rand(2,3) # => included 0.0 exluded 1.0
print(a)

[[0.326929   0.89052565 0.22733259]
 [0.28152191 0.5960954  0.85706907]]
